version: "3.9"

services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      # - laravel-api-vendor:/var/www/backend-api/vendor
      - ./services/:/var/www/
      - ./config/nginx/:/etc/nginx/sites-enabled/

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo-database:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongodb:27017?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-database:
  # laravel-api-vendor:
